name: PandoraBooster
version: ${project.version}
main: me.nanigans.pandorabooster.PandoraBooster
api-version: 1.16
authors: [ProNanigans]
description: A booster plugin for PandoraPvp
commands:
  givebooster:
    usage: /givebooster <player> <boostername> <amount>
    description: Gives the player a booster item,
    aliases: [giveboost, gb, boost, boostgive]
