name: PandoraBooster
version: ${project.version}
main: me.nanigans.pandorabooster.PandoraBooster
api-version: 1.16
authors: [ProNanigans]
description: A booster plugin for PandoraPvp
commands:
  givebooster:
    usage: /givebooster <player> <boostername> <amount>
    description: Gives the player a booster item,
    aliases: [giveboost, gb, boost, boostgive]
  currentboosters:
    usage: /currentboosters <player>
    description: Shows the current boosts a you or a player has
    aliases: [cb, currentboosts, boosts, showboosts]
permissions:
  Boosters.SeeOthers:
    description: Allows the user to see other players boosters
    default: op
  Boosters.GiveOut:
    description: Allows the user to create new boosters
    default: op
